### PR TITLE
Add pre-commit-yaml from nova/master

### PR DESCRIPTION
**Pull request by fwiesel**
This way we stay more close the upstream also
in the development process

Change-Id: I51d9340205ddaa1266441347dac0c47ff05ec9f0

### CODE REVIEW

**Review by joker-at-work — APPROVED** [review]
If you want that, sure.

Is there a tox env testing all those things, too? Could we activate it in the CI?

**Comment by fwiesel** [comment]
> Is there a tox env testing all those things, too?

I am not quite sure what you mean by that.

>  Could we activate it in the CI?

Yes, apparently there is a command for it `pre-commit run --from-ref origin/HEAD --to-ref HEAD`.
We could also consider enabling https://pre-commit.ci

**Comment by joker-at-work** [comment]
> > Is there a tox env testing all those things, too?
> 
> I am not quite sure what you mean by that.

I was wondering if there's something in [here](https://github.com/sapcc/nova/blob/stable/rocky-m3/tox.ini) to mimic that behavior, so we can easily integrate that into our pull-requests CI. I was only aware of the flake8 tests until now. How does upstream ensure this is valid, if the user didn't activate pre-commit before creating a review-request?

**Comment by fwiesel** [comment]
From my view, the two things are somewhat decoupled, and the way I see it, it is also handled separately in upstream.

One is having tools to bring the source code in the desired shape (e.g. pre-commit), and the other is validating that the code is conforming to the required standard (Zool -> Tox -> ...).

The pre-commit tool is just a recommendation you can opt-in to make your live easier to achieve the result according to the standard, which is enforced in the pipeline. You are still free to do it differently (e.g. by hand).

I followed the recommendation when upstreaming my changes, but now it complains about a missing configuration in our branch.

**Pull request merged**
