### PR TITLE
HANA-NUMA alignment for xena

### PR DESCRIPTION
**Pull request by grandchild**
- vmware: Set preferHT on all CUSTOM_NUMASIZE flavors
- vmware: Restart BigVMs with "high" priority
- vmware: Set maxPerVirtualNode for HANA flavors

### CODE REVIEW

**Comment by grandchild** [comment]
Same as #387.

**Review by fwiesel — APPROVED** [review]

**Review by fwiesel — CHANGES_REQUESTED** [review]
Looks like the merged duplicated some functions, the unit tests fail

**Comment by grandchild** [comment]
Sloppy cherry-pick conflict resolution from my side. Thanks unit tests!

**Comment by fwiesel** [comment]
One flake8 test fix and you're good to go :)

**Comment by grandchild** [comment]
@fwiesel would you do the honors one last time? :)

**Pull request merged**
