### PR TITLE
Support bfv rescue

### PR DESCRIPTION
**Pull request by joker-at-work**
Please see the individual commits' messages.

### CODE REVIEW

**Review by grandchild — APPROVED** [review]
Code looks good, has it been tested yet?

**Comment by joker-at-work** [comment]
no tests have happened - and the tests even fail :)

**Comment by joker-at-work** [comment]
Had to rewrite it a little to get the tests to work. Hasn't been tested in a real system, yet, though.

**Review by grandchild — APPROVED** [review]

**Comment by joker-at-work** [comment]
now tested in qa

**Pull request merged**
