### PR TITLE
[vmware] replace serial ports when creating instance from image template

### PR DESCRIPTION
**Pull request by imitevm**

### CODE REVIEW

**Comment by notandy** [comment]
lgfm

**Comment by imitevm** [comment]
I could but what's the idea behind using isinstance()? Those are Vim object hence the classes are dynamically generated and we'd still need to use strings to [generate the class objects](https://github.com/sapcc/suds-jurko/blob/master/suds/sudsobject.py#L105) for the isinstance() parameter. If the intent is to avoid referring to class by name then isinstance() won't do the work in this case.

**Comment by fwiesel** [comment]
My problem is less with using strings, but with the `__class__.__name__` access and comparison.
`isinstance` also covers derived classes. I am fine, if you use strings to get/define the "right-hand side" of the comparison.

**Comment by imitevm** [comment]
Actually, it won't cover the inheritance anyway as the Vim classes are constructed as [derived from Object](https://github.com/sapcc/suds-jurko/blob/master/suds/sudsobject.py#L120). I'll rework it with isinstance to get rid of the private access at least.

**Comment by fwiesel** [comment]
Thanks, looks great.

**Pull request merged**
