### PR TITLE
baremetal quota handling, Queens edition

### PR DESCRIPTION
**Pull request by majewsky**
This is mostly a straight-forward port of #16.

@fwiesel I have not tested this yet since we don't have a Nova DB anywhere with the required migrations yet. If you want to hold this PR back until I can test it in QA, that's fine by me.

~~WIP: I need to go through the `stable/mitaka-m3` branch for all those nitty-gritty fixes that I did after #16 was already merged.~~

### CODE REVIEW

**Comment by majewsky** [comment]
@fwiesel Any updates here? The Queens upgrade in staging is underway afaik, so we probably want to have this in at some point.

**Comment by fwiesel** [comment]
Fine by me.
But we are postponing the upgrade of nova. We probably have to go to a intermediate version as the db upgrades are not handling from mitaka to queens.

**Comment by majewsky** [comment]
Okay, then let's wait until the DB is upgraded to Queens in staging.

**Comment by fwiesel** [comment]
Let's give it a try

**Pull request merged**
