### PR TITLE
Update vm host drs

### PR DESCRIPTION
**Pull request by mmidolesov**

### CODE REVIEW

**Comment by fwiesel** [comment]
Hi, that change hasn't been merged yet.

**Comment by notandy** [comment]
Urgh, what does it change?  I thought all necessary changes were already merged

**Comment by notandy** [comment]
I also see most of the changes are already incorporated, this changeset is far too huge

**Comment by fwiesel** [comment]
@mmidolesov Could you rebase the patch again? Thanks

**Comment by mmidolesov** [comment]
Ill change it.

**Comment by fwiesel** [comment]
Not working on queens anymore.

**Pull request closed without merging**
