### PR TITLE
bigvm: SchedulerReportClient._ensure_resource_class got renamed

### PR DESCRIPTION
**Pull request by joker-official**
We need to call _ensure_resource_classes instead.

Change-Id: I2329db43adc00e04b07d16d312361ae5e669d298

### CODE REVIEW

**Comment by grandchild** [comment]
How about changing
https://github.com/sapcc/nova/blob/5373a2e5dcf46c3699a8cf81f38f19baa258da98/nova/scheduler/client/report.py#L1051
and
https://github.com/sapcc/nova/blob/5373a2e5dcf46c3699a8cf81f38f19baa258da98/nova/scheduler/client/report.py#L1093
as well?

**Comment by joker-official** [comment]
> How about changing
> https://github.com/sapcc/nova/blob/5373a2e5dcf46c3699a8cf81f38f19baa258da98/nova/scheduler/client/report.py#L1051
> 
> 
> and
> https://github.com/sapcc/nova/blob/5373a2e5dcf46c3699a8cf81f38f19baa258da98/nova/scheduler/client/report.py#L1093
> 
> 
> as well?

Would be something to propose to upstream not to change nova-bigvm to still work, wouldn't it?

**Comment by grandchild** [comment]
Sure, that as well, but maybe also something for our fork. It looks like the comments might've been the source of the error.

If you think it doesn't belong here, I'm fine with it.

**Comment by joker-official** [comment]
The comments didn't get changed together with the function. [Here's](https://github.com/sapcc/nova/blob/stable/queens-m3/nova/scheduler/client/report.py#L1276) the queens version.

**Review by grandchild — APPROVED** [review]
> The comments didn't get changed together with the function

Ah I see... Alright.

One of the comments [still survives in upstream](https://github.com/openstack/nova/blob/e7aa436dc6158a124529bb64b1d98e5c95596236/nova/scheduler/client/report.py#L885)

**Pull request merged**
